### PR TITLE
Add the option to include hashes in the idtoken

### PR DESCRIPTION
**Pull request by nsklikas**
Add the options `add_c_hash` and `add_at_hash` to retrieve the tokens from
the session_info and add their hashes to the id token

### CODE REVIEW

**Review by peppelinux — APPROVED** [review]
Clean code, looks good.
It seems ready to be merged, good to have that claims in

**Comment by rohe** [comment]
c_hash and at_hash should be added to the ID Token when they according to the OIDC standards should be there. 
I do that way in the new session management code.

**Comment by peppelinux** [comment]
> c_hash and at_hash should be added to the ID Token when they according to the OIDC standards should be there.
> I do that way in the new session management code.

Do we have to reject this or adapt the session manager on top of this latter commits?

**Comment by rohe** [comment]
First, I don't understand why c_hash and at_hash are not already automagically added. They should be.
Secondly, the new session code is not approved yet. Don't know how long that will take. So waiting for the new code to be accepted may take a while. I don't see how this could hurt us in the mean time.

**Pull request merged**
