### PR TITLE
Add claims per client in id token

### PR DESCRIPTION
**Pull request by nsklikas**
Adds the `id_token_claims` to clients, which is used to add specific claims per client to the id token.

This would give the ability to the clients to choose any set of claims they want when the registration endpoint is activated, but they would be able to do that nonetheless by using the claims parameter. Maybe we should add an option to limit the claims that can be included in an id token(e.g. "allowed_claims")?

### CODE REVIEW

**Comment by rohe** [comment]
I don't get the new test's name seems to me it's more about client claims enabled then client claims disabled. Or am I missing something ?

**Comment by nsklikas** [comment]
The `enable_claims_per_client` parameter defaults to None(False). 
In the `test_client_claims_disabled` test I don't set it to anything so it defaults to None (ie claims per client are disabled).

Do you think I should change rename something or simply add `self.endpoint_context.idtoken.enable_claims_per_client = False` to the last test for clarity?

**Comment by rohe** [comment]
Maybe not explicitly set it to False but at least there should be a comment about what the default is.

**Comment by nsklikas** [comment]
Ok

**Pull request merged**
