### PR TITLE
nightly contributions

### PR DESCRIPTION
**Pull request by peppelinux**
little things in endpoint_context.py

Fixed: tests/test_24_authorization_endpoint.py
Sometimes test_inputs fails for input elements order

I get in tests/test_26_userinfo_endpoint.py
ImportError: No module named 'oidcendpoint.oidc.add_on.custom_scopes'
and yes it's missing. Is it still to be committed?

Then test_30_end_session.py: got many failures.
Fixed some of them regarding url-args ordering but cookie with "wrong client" error
and another KeyError still need to be patched.

### CODE REVIEW

**Comment by rohe** [comment]
Was this running the latest code ?
I don't get any test failures, ever.

**Comment by peppelinux** [comment]
I used an env with py35.
The bad news: The errors seems randomic, It isnt't the First Time I see these kind of problems from py35 to py36 and 37 and viceversa.

But I cannot undetsrand why sometimes client_1 in the cookie became client_2 🙃
Bytheway if you see the commits they seems not influent to these problems

I can check them much Better if needed, no hurry

**Comment by rohe** [comment]
So, should we drop support for py35 ? 
I run only py37.

client_1 becoming client_2 is really weird.
Consistent for one and the same test ?

**Comment by peppelinux** [comment]
Those 3 tests, randomly.
I already faced this problem in other platforms.
What's coded in py37 (dict) have different behaviour on sorting.
Nothing new, I'm on it, I'll give you more acknowledges soon

**Comment by rohe** [comment]
Ah, sorting ! Yeah, know about that.

**Comment by peppelinux** [comment]
Added Travis CI to oidcendpoint
https://travis-ci.com/peppelinux/oidcendpoint

Yes, let's drop py3.5.
See .travis.yml for details

**Comment by rohe** [comment]
py35 was actually removed from setup.py a while back :-)

**Comment by peppelinux** [comment]
I'll compile a py37 to a netbook of mine (the nightly One) with ubnt16.04, an ordinary task nowadays.
I confligured Travis with a debian10 (buster) only, you should attach idpy travis bot to this repository otherwise It triggers only to my repo commits/PR.

Whatelse? I'll configure tox/tests in travis.yml in 24 h, I'm doing this kind of things with my smartphone (Crazy things)
Day Is done, nice shoot

**Pull request merged**
