### PR TITLE
Allow token audience in _make_at

### PR DESCRIPTION
**Pull request by jschlyter**
Also, allow aud as list in JWT Tokten

### CODE REVIEW

**Comment by rohe** [comment]
So this is not an ID Token so there is no rule about that the client_id MUST be one of the aud values but what's the reason for not letting it be in there by default.

**Comment by jschlyter** [comment]
I'm thinking that if one want to have the client_id in the audience, one can add it. No strong feeling about this though - just say the magic word and I'll add it as default.

**Comment by rohe** [comment]
I wonder how common it is that an RP is asking for an access token but never intends to use it itself, but always turns it over to some other entity ?
And the flip side of that, why would the OP want to prevent the RP from using the token ?

**Comment by jschlyter** [comment]
You want aud to always include the client_id?

**Comment by rohe** [comment]
Basically yes. 
Right now when you init the JWTToken class you can give it a static set of aud values to add to all produced JWTs. Perhaps we should have a configuration option that meant that the client_id always would be added.

**Comment by jschlyter** [comment]
The client_id is added to the aud by `SessionDB._make_at`. I've added an option NOT to include the client_id in the aud now, hope this is reasonable.

**Pull request merged**
